<a href="https://colab.research.google.com/github/charlien12/ML-Projects/blob/main/DateFruit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df=pd.read_csv('DateFruit_Dataset.csv')

In [2]:
df.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [4]:
display(df.isnull().sum())
display(df.shape)

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

(898, 35)

In [5]:
X=df.drop('Class',axis=1)
Y=df['Class']

In [6]:
from sklearn.preprocessing import StandardScaler,LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [8]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

# ANN Model And Evaluation

In [9]:
import torch.nn as nn
import torch

In [11]:
X_train_tensor=torch.tensor(X_train_scaled,dtype=torch.float32)
Y_train_tensor=torch.tensor(Y_train,dtype=torch.long)
X_test_tensor=torch.tensor(X_test_scaled,dtype=torch.float32)
Y_test_tensor=torch.tensor(Y_test,dtype=torch.long)

In [12]:
from torch.utils.data import TensorDataset,DataLoader

In [13]:
train_dataset=TensorDataset(X_train_tensor,Y_train_tensor)
test_dataset=TensorDataset(X_test_tensor,Y_test_tensor)

In [14]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=False)

In [15]:
class ANN(nn.Module):
  def __init__(self):
    super(ANN, self).__init__()
    self.model=nn.Sequential(
      nn.Linear(X_train.shape[1],64),
      nn.ReLU(),
      nn.Linear(64,64),
      nn.ReLU(),
      nn.Linear(64,7))
  def forward(self,x):
    return self.model(x)

In [16]:
import torch.optim as optim
model=ANN()
criterion=nn.CrossEntropyLoss()
optimizer=optim.Adam(model.parameters())

# Training the NN

In [17]:
epochs=100
for epoch in range(epochs):
  model.train()
  running_loss=0.0
  for xb,yb in train_loader:
    outputs=model(xb)
    loss=criterion(outputs,yb)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    running_loss+=loss.item()
  train_loss=running_loss/len(train_loader)
  print(f"epoch {epoch+1}/{epochs} ==> train loss = {train_loss}")

epoch 1/100 ==> train loss = 1.7371463464654011
epoch 2/100 ==> train loss = 1.1322438716888428
epoch 3/100 ==> train loss = 0.7201356447261312
epoch 4/100 ==> train loss = 0.5416882660077966
epoch 5/100 ==> train loss = 0.4445368990949962
epoch 6/100 ==> train loss = 0.3914415480002113
epoch 7/100 ==> train loss = 0.3504020085801249
epoch 8/100 ==> train loss = 0.3144878965357076
epoch 9/100 ==> train loss = 0.29334314847769943
epoch 10/100 ==> train loss = 0.2697457561026449
epoch 11/100 ==> train loss = 0.2553390860557556
epoch 12/100 ==> train loss = 0.2398352914530298
epoch 13/100 ==> train loss = 0.2246024498473043
epoch 14/100 ==> train loss = 0.21251586209172788
epoch 15/100 ==> train loss = 0.20700368997843369
epoch 16/100 ==> train loss = 0.20358210154201672
epoch 17/100 ==> train loss = 0.19322454151899918
epoch 18/100 ==> train loss = 0.1797564781230429
epoch 19/100 ==> train loss = 0.1821123225533444
epoch 20/100 ==> train loss = 0.1704150551687116
epoch 21/100 ==> train loss = 0.1626342042632725
epoch 22/100 ==> train loss = 0.1627916466930638
epoch 23/100 ==> train loss = 0.15355549104835675
epoch 24/100 ==> train loss = 0.14790362654172856
epoch 25/100 ==> train loss = 0.1449729486004166
epoch 26/100 ==> train loss = 0.13922578080192857
epoch 27/100 ==> train loss = 0.1337520685856757
epoch 28/100 ==> train loss = 0.1330516895522242
epoch 29/100 ==> train loss = 0.13467550812208134
epoch 30/100 ==> train loss = 0.12618822798780774
epoch 31/100 ==> train loss = 0.1198235547736935
epoch 32/100 ==> train loss = 0.12293170198150304
epoch 33/100 ==> train loss = 0.11377919343826563
epoch 34/100 ==> train loss = 0.11672510109517885
epoch 35/100 ==> train loss = 0.11509322705071258
epoch 36/100 ==> train loss = 0.12066697726107162
epoch 37/100 ==> train loss = 0.1170930072017338
epoch 38/100 ==> train loss = 0.12488985235762337
epoch 39/100 ==> train loss = 0.11500255698743074
epoch 40/100 ==> train loss = 0.10522147033201612
epoch 41/100 ==> train loss = 0.10315984220284483
epoch 42/100 ==> train loss = 0.10332065059438995
epoch 43/100 ==> train loss = 0.10133769703300102
epoch 44/100 ==> train loss = 0.1009095531442891
epoch 45/100 ==> train loss = 0.09700969007352124
epoch 46/100 ==> train loss = 0.09034780740899884
epoch 47/100 ==> train loss = 0.08419064760370099
epoch 48/100 ==> train loss = 0.09453333728015423
epoch 49/100 ==> train loss = 0.08734461584168932
epoch 50/100 ==> train loss = 0.08203270513078441
epoch 51/100 ==> train loss = 0.08221324610159449
epoch 52/100 ==> train loss = 0.07970612123608589
epoch 53/100 ==> train loss = 0.07537206197562425
epoch 54/100 ==> train loss = 0.07869044051546117
epoch 55/100 ==> train loss = 0.07323650195789726
epoch 56/100 ==> train loss = 0.07985619042554627
epoch 57/100 ==> train loss = 0.07115349295022695
epoch 58/100 ==> train loss = 0.0740804886850326
epoch 59/100 ==> train loss = 0.06883342507416787
epoch 60/100 ==> train loss = 0.06937100268576456
epoch 61/100 ==> train loss = 0.06538853138361288
epoch 62/100 ==> train loss = 0.06736267017929451
epoch 63/100 ==> train loss = 0.06965420010459164
epoch 64/100 ==> train loss = 0.06363289572460495
epoch 65/100 ==> train loss = 0.06291206015030974
epoch 66/100 ==> train loss = 0.06083504479054524
epoch 67/100 ==> train loss = 0.06022656052980734
epoch 68/100 ==> train loss = 0.05735814312229986
epoch 69/100 ==> train loss = 0.05629717975692904
epoch 70/100 ==> train loss = 0.06321698406954175
epoch 71/100 ==> train loss = 0.058322623210108795
epoch 72/100 ==> train loss = 0.05921557869600213
epoch 73/100 ==> train loss = 0.05263374709402737
epoch 74/100 ==> train loss = 0.04962845940304839
epoch 75/100 ==> train loss = 0.05118446059160582
epoch 76/100 ==> train loss = 0.04862833662849406
epoch 77/100 ==> train loss = 0.05207601477108572
epoch 78/100 ==> train loss = 0.045596589577262814
epoch 79/100 ==> train loss = 0.046154124702772366
epoch 80/100 ==> train loss = 0.04608717455488184
epoch 81/100 ==> train loss = 0.04526630946961434
epoch 82/100 ==> train loss = 0.04413223981290408
epoch 83/100 ==> train loss = 0.044283467608139566
epoch 84/100 ==> train loss = 0.040254003611271794
epoch 85/100 ==> train loss = 0.04267286592284623
epoch 86/100 ==> train loss = 0.03711967907198097
epoch 87/100 ==> train loss = 0.0408458712146334
epoch 88/100 ==> train loss = 0.0370874374942935
epoch 89/100 ==> train loss = 0.03384093529261325
epoch 90/100 ==> train loss = 0.03454639620916999
epoch 91/100 ==> train loss = 0.03368574625852963
epoch 92/100 ==> train loss = 0.03397962392267326
epoch 93/100 ==> train loss = 0.034872021364129105
epoch 94/100 ==> train loss = 0.04325865624148561
epoch 95/100 ==> train loss = 0.033171100420472416
epoch 96/100 ==> train loss = 0.0325448053949715
epoch 97/100 ==> train loss = 0.032869549873082535
epoch 98/100 ==> train loss = 0.03568964172154665
epoch 99/100 ==> train loss = 0.030052711498802124
epoch 100/100 ==> train loss = 0.02822095714509487

# Evaluation

In [19]:
model.eval()
total=0
correct=0
with torch.no_grad():
  for xb,yb in test_loader:
    outputs=model(xb)
    _,predicted=torch.max(outputs,1)
    total+=yb.size(0)
    correct+=(predicted==yb).sum().item()
print(f"Accuracy on test set: {100*correct/total}%")
print(f"Number of correct predictions: {correct}")
print(f"Number of total predictions: {total}")

Accuracy on test set: 95.0%
Number of correct predictions: 171
Number of total predictions: 180